version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: shine_stn_app_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # <名前付きvolume名>:マウントしたいコンテナ内のPATH
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/shine_stn_app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata: # 名前付きvolumeを定義

