version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: shine_stn_app_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: sh -c "rm -f /shine_stn_app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/shine_stn_app
    ports:
      - "3000:3000"
    depends_on:
      - db
  css:
    build: .
    command: bundle exec rails dartsass:watch
    volumes:
      - .:/shine_stn_app
    depends_on:
      - web
volumes:
  pgdata:
