default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: blast_stn_knowledge_pass
  pool: 5

development:
  <<: *default
  database: blast_stn_knowledge_development

test:
  <<: *default
  database: blast_stn_knowledge_test

production:
  <<: *default
  database: blast_stn_knowledge_production
  username: <%= ENV["BLAST_STN_DATABASE_USER"] %>
  host: <%= ENV["BLAST_STN_DATABASE_HOST"] %>
  password: <%= ENV["BLAST_STN_DATABASE_PASSWORD"] %>
